modLoader="javafml"
loaderVersion="[58,)"
license="MIT"

[[mods]]
modId="holamundo"
version="1.0.0"
displayName="Hola Mundo"
description='Un mod de prueba'

[[dependencies.holamundo]]
modId="minecraft"
mandatory=true
versionRange="[1.21.8,)"
ordering="NONE"
side="BOTH"
