modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="holamundo"
version="1.0.0"
displayName="Hola Mundo Mod"
description="Un mod de ejemplo que dice Hola Mundo en Minecraft Forge 1.21.8"
